package:
  name: destruct
  version: '0.4.22'

source:
  git_url: https://github.com/amcpherson/destruct.git
  git_rev: v0.4.22

build:
  number: 1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - pandas
    - pypeliner
    - pygenes
    - bowtie
    - pyyaml
    - matplotlib
    - seaborn
    - pysam

about:
  home: http://bitbucket.org/dranew/destruct
  license: MIT
  summary: 'Bioinformatics tool for joint prediction of rearrangement breakpoints from single or multiple tumour samples'

