package:
  name: destruct
  version: '0.4.19'

source:
  git_url: git://github.com/amcpherson/destruct.git
  git_rev: v0.4.19

build:
  number: 1

requirements:
  build:
    - python
    - numpy==1.19.2

  run:
    - python
    - numpy==1.19.2
    - pandas
    - pypeliner
    - pygenes
    - bowtie
    - pyyaml
    - matplotlib
    - seaborn
    - pysam

about:
  home: http://bitbucket.org/dranew/destruct
  license: MIT
  summary: 'Bioinformatics tool for joint prediction of rearrangement breakpoints from single or multiple tumour samples'

